/*lob_schema_definition*/
CREATE SCHEMA SYSTEM_LOBS AUTHORIZATION DBA
 CREATE TABLE BLOCKS(BLOCK_ADDR INT, BLOCK_COUNT INT, TX_ID BIGINT, PRIMARY KEY(BLOCK_ADDR))
 CREATE INDEX BLOCKS_IDX1 ON BLOCKS(BLOCK_COUNT)
 CREATE INDEX BLOCKS_IDX2 ON BLOCKS(TX_ID)
 CREATE TABLE LOBS(BLOCK_ADDR INT, BLOCK_COUNT INT, BLOCK_ORDER INT, LOB_ID BIGINT, LOB_LENGTH BIGINT,
  PRIMARY KEY(LOB_ID, BLOCK_ORDER), UNIQUE(LOB_ID, BLOCK_ADDR), UNIQUE(BLOCK_ADDR) )
 CREATE INDEX LOBS_IDX1 ON LOBS(LOB_ID, BLOCK_COUNT)

 CREATE PROCEDURE CONVERT_BLOCK(B_ADDR INT, B_COUNT INT, B_ORDER INT, L_ID BIGINT, L_LENGTH BIGINT)
  MODIFIES SQL DATA BEGIN ATOMIC
  DELETE FROM BLOCKS WHERE BLOCK_ADDR = B_ADDR;
  INSERT INTO LOBS VALUES(B_ADDR, B_COUNT, B_ORDER, L_ID, L_LENGTH);
  END

 CREATE PROCEDURE DELETE_LOB(L_ID BIGINT, TX_ID BIGINT)
  MODIFIES SQL DATA BEGIN ATOMIC
  INSERT INTO BLOCKS (SELECT BLOCK_ADDR,BLOCK_COUNT,TX_ID FROM LOBS WHERE LOB_ID = L_ID);
  DELETE FROM LOBS WHERE LOB_ID = L_ID;
  END

 CREATE PROCEDURE CREATE_EMPTY_BLOCK(INOUT B_ADDR INT, IN B_COUNT INT)
  MODIFIES SQL DATA BEGIN ATOMIC
  DECLARE TEMP_COUNT INT DEFAULT NULL;
  DECLARE TEMP_ADDR INT DEFAULT NULL;
  SET (TEMP_ADDR, TEMP_COUNT) = (SELECT BLOCK_ADDR, BLOCK_COUNT FROM BLOCKS WHERE BLOCK_COUNT > B_COUNT AND TX_ID = 0 FETCH 1 ROW ONLY);
  UPDATE BLOCKS SET BLOCK_COUNT = B_COUNT WHERE BLOCK_ADDR = TEMP_ADDR;
  INSERT INTO BLOCKS VALUES (TEMP_ADDR + B_COUNT, TEMP_COUNT - B_COUNT, 0);
  SET B_ADDR = TEMP_ADDR;
  END

 CREATE PROCEDURE ALLOC_BLOCKS (OUT L_ADDR INT, IN B_COUNT INT, IN B_ORDER INT, IN L_ID BIGINT, IN L_LENGTH BIGINT)
  MODIFIES SQL DATA BEGIN ATOMIC

  DECLARE LOB_ADDR INT DEFAULT NULL;
  DECLARE TOTAL_COUNT INT DEFAULT 0;
  DECLARE BL_ADDR INT DEFAULT NULL;
  DECLARE TEMP_COUNT INT DEFAULT 0;
  DECLARE BL_ORDER INT DEFAULT 0;

  SET TOTAL_COUNT = B_COUNT;
  SET BL_ORDER = B_ORDER;

  MAIN_LOOP: LOOP

   SET BL_ADDR = (SELECT BLOCK_ADDR FROM BLOCKS WHERE BLOCK_COUNT = B_COUNT AND TX_ID = 0 FETCH 1 ROW ONLY);

   IF BL_ADDR IS NOT NULL THEN

    CALL CONVERT_BLOCK (BL_ADDR, TOTAL_COUNT, BL_ORDER, L_ID, CASE WHEN LOB_ADDR IS NULL THEN L_LENGTH ELSE NULL END CASE);

    IF LOB_ADDR IS NULL THEN
     SET LOB_ADDR = BL_ADDR;
    END IF;

    SET L_ADDR = LOB_ADDR;

    LEAVE MAIN_LOOP;

   END IF;

   SET (BL_ADDR, TEMP_COUNT) = (SELECT BLOCK_ADDR, BLOCK_COUNT FROM BLOCKS WHERE BLOCK_COUNT < B_COUNT AND TX_ID = 0 FETCH 1 ROW ONLY);

   IF BL_ADDR IS NOT NULL THEN

    CALL CONVERT_BLOCK (BL_ADDR, TOTAL_COUNT, BL_ORDER, L_ID, CASE WHEN LOB_ADDR IS NULL THEN L_LENGTH ELSE NULL END CASE);

    IF LOB_ADDR IS NULL THEN
      SET LOB_ADDR = BL_ADDR;
    END IF;

    SET TOTAL_COUNT = TOTAL_COUNT - TEMP_COUNT;
    SET BL_ORDER = BL_ORDER + 1;
    SET BL_ADDR = NULL;
    SET TEMP_COUNT = 0;

   ELSE

    CALL CREATE_EMPTY_BLOCK (BL_ADDR, TOTAL_COUNT);
    CALL CONVERT_BLOCK (BL_ADDR, TOTAL_COUNT, BL_ORDER, L_ID, CASE WHEN LOB_ADDR IS NULL THEN L_LENGTH ELSE NULL END CASE);

    IF LOB_ADDR IS NULL THEN
     SET LOB_ADDR = BL_ADDR;
     SET L_ADDR = LOB_ADDR;
     LEAVE MAIN_LOOP;
    END IF;

   END IF;

  END LOOP MAIN_LOOP;
 END
;

/*get_lob_query*/
SELECT * FROM LOBS WHERE LOB_ID = ?;
/*get_lob_part_statement*/
SELECT * FROM LOBS WHERE LOB_ID = ? ORDER BY BLOCK_ORDER OFFSET ? FETCH ? ROWS ONLY;
