-- E031_Identifiers_03_Trailing_underscore.sql
DROP TABLE IF EXISTS TEST_;
CREATE TABLE TEST_(ID_ INT);
SELECT COUNT(*) AS TABLE_COUNT FROM INFORMATION_SCHEMA.TABLES T WHERE T.TABLE_SCHEMA = 'PUBLIC' AND T.TABLE_NAME = 'TEST_';
ALTER TABLE TEST_ ADD COLUMN VALUE_ VARCHAR(255) NOT NULL;
SELECT COUNT(*) AS COLUMN_COUNT FROM INFORMATION_SCHEMA.COLUMNS T WHERE T.TABLE_SCHEMA = 'PUBLIC' AND T.TABLE_NAME = 'TEST_' AND T.COLUMN_NAME = 'VALUE_';
ALTER TABLE TEST_ DROP COLUMN VALUE_;
SELECT COUNT(*)  AS COLUMN_COUNT FROM INFORMATION_SCHEMA.COLUMNS T WHERE T.TABLE_SCHEMA = 'PUBLIC' AND T.TABLE_NAME = 'TEST_' AND T.COLUMN_NAME = 'VALUE_';
DROP TABLE TEST_;
SELECT COUNT(*) AS TABLE_COUNT FROM INFORMATION_SCHEMA.TABLES T WHERE T.TABLE_SCHEMA = 'PUBLIC' AND T.TABLE_NAME = 'TEST_';

