-- Test of SQL Feasture E03 - Identifiers, Subfeatrure 03 - Trailing underscore
/*s*/DROP TABLE IF EXISTS TEST_;
/*s*/CREATE TABLE TEST_(ID_ INT);
/*c1*/SELECT COUNT(*) AS TABLE_COUNT FROM INFORMATION_SCHEMA.TABLES T WHERE T.TABLE_SCHEMA = 'PUBLIC' AND T.TABLE_NAME = 'TEST_';
/*s*/ALTER TABLE TEST_ ADD COLUMN VALUE_ VARCHAR(255) NOT NULL;
/*c1*/SELECT COUNT(*) AS COLUMN_COUNT FROM INFORMATION_SCHEMA.COLUMNS T WHERE T.TABLE_SCHEMA = 'PUBLIC' AND T.TABLE_NAME = 'TEST_' AND T.COLUMN_NAME = 'VALUE_';
/*s*/ALTER TABLE TEST_ DROP COLUMN VALUE_;
/*c1*/SELECT COUNT(*)  AS COLUMN_COUNT FROM INFORMATION_SCHEMA.COLUMNS T WHERE T.TABLE_SCHEMA = 'PUBLIC' AND T.TABLE_NAME = 'TEST_' AND T.COLUMN_NAME = 'VALUE_';
/*s*/DROP TABLE TEST_;
/*c1*/SELECT COUNT(*) AS TABLE_COUNT FROM INFORMATION_SCHEMA.TABLES T WHERE T.TABLE_SCHEMA = 'PUBLIC' AND T.TABLE_NAME = 'TEST_';

