/* Copyright (c) 2001-2007, The HSQL Development Group
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * Neither the name of the HSQL Development Group nor the names of its
 * contributors may be used to endorse or promote products derived from this
 * software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL HSQL DEVELOPMENT GROUP, HSQLDB.ORG,
 * OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */


package org.hsqldb;

import org.hsqldb.lib.HashSet;
import org.hsqldb.lib.IntValueHashMap;
import org.hsqldb.lib.OrderedIntHashSet;

/**
 * Defines and enumerates reserved and non-reserved SQL
 * keywords. <p>
 *
 * @author  Nitin Chauhan
 * @author  fredt@users
 * @version 1.9.0
 * @since 1.7.2
 */
public class Token {

    //
    // SQL 200n reserved words full set
    static final String        T_ABS              = "ABS";
    public static final String T_ALL              = "ALL";
    static final String        T_ALLOCATE         = "ALLOCATE";
    public static final String T_ALTER            = "ALTER";
    static final String        T_AND              = "AND";
    static final String        T_ANY              = "ANY";
    static final String        T_ARE              = "ARE";
    static final String        T_ARRAY            = "ARRAY";
    static final String        T_AS               = "AS";
    static final String        T_ASENSITIVE       = "ASENSITIVE";
    static final String        T_ASYMMETRIC       = "ASYMMETRIC";
    static final String        T_AT               = "AT";
    static final String        T_ATOMIC           = "ATOMIC";
    static final String        T_AUTHORIZATION    = "AUTHORIZATION";
    static final String        T_AVG              = "AVG";
    static final String        T_BEGIN            = "BEGIN";
    static final String        T_BETWEEN          = "BETWEEN";
    public static final String T_BIGINT           = "BIGINT";
    public static final String T_BINARY           = "BINARY";
    public static final String T_BLOB             = "BLOB";
    public static final String T_BOOLEAN          = "BOOLEAN";
    static final String        T_BOTH             = "BOTH";
    static final String        T_BY               = "BY";
    static final String        T_CALL             = "CALL";
    static final String        T_CALLED           = "CALLED";
    static final String        T_CARDINALITY      = "CARDINALITY";
    static final String        T_CASCADED         = "CASCADED";
    static final String        T_CASE             = "CASE";
    static final String        T_CAST             = "CAST";
    static final String        T_CEIL             = "CEIL";
    static final String        T_CEILING          = "CEILING";
    static final String        T_CHAR             = "CHAR";
    static final String        T_CHAR_LENGTH      = "CHAR_LENGTH";
    public static final String T_CHARACTER        = "CHARACTER";
    static final String        T_CHARACTER_LENGTH = "CHARACTER_LENGTH";
    static final String        T_CHECK            = "CHECK";
    public static final String T_CLOB             = "CLOB";
    static final String        T_CLOSE            = "CLOSE";
    static final String        T_COALESCE         = "COALESCE";
    static final String        T_COLLATE          = "COLLATE";
    static final String        T_COLLECT          = "COLLECT";
    static final String        T_COLUMN           = "COLUMN";
    public static final String T_COMMIT           = "COMMIT";
    static final String        T_CONDITION        = "CONDIITON";
    public static final String T_CONNECT          = "CONNECT";
    static final String        T_CONSTRAINT       = "CONSTRAINT";
    static final String        T_CONVERT          = "CONVERT";
    static final String        T_CORR             = "CORR";
    static final String        T_CORRESPONDING    = "CORRESPONDING";
    static final String        T_COUNT            = "COUNT";
    static final String        T_CONVAR_POP       = "CONVAR_POP";
    static final String        T_CONVAR_SAMP      = "CONVAR_SAMP";
    public static final String T_CREATE           = "CREATE";
    static final String        T_CROSS            = "CROSS";
    static final String        T_CUBE             = "CUBE";
    static final String        T_CUME_DIST        = "CUME_DIST";
    static final String        T_CURRENT          = "CURRENT";
    static final String        T_CURRENT_CATALOG  = "CURRENT_CATALOG";
    static final String        T_CURRENT_DATE     = "CURRENT_DATE";
    static final String T_CURRENT_DEFAULT_TRANSFORM_GROUP =
        "CURRENT_DEFAULT_TRANSFORM_GROUP";
    static final String T_CURRENT_PATH      = "CURRENT_PATH";
    static final String T_CURRENT_ROLE      = "CURRENT_ROLE";
    static final String T_CURRENT_SCHEMA    = "CURRENT_SCHEMA";
    static final String T_CURRENT_TIME      = "CURRENT_TIME";
    static final String T_CURRENT_TIMESTAMP = "CURRENT_TIMESTAMP";
    static final String T_CURRENT_TRANSFORM_GROUP_FOR_TYPE =
        "CURRENT_TRANSFORM_GROUP_FOR_TYPE";
    static final String        T_CURRENT_USER      = "CURRENT_USER";
    static final String        T_CURSOR            = "CURSOR";
    static final String        T_CYCLE             = "CYCLE";
    public static final String T_DATE              = "DATE";
    public static final String T_DAY               = "DAY";
    static final String        T_DEALLOCATE        = "DEALLOCATE";
    static final String        T_DEC               = "DEC";
    public static final String T_DECIMAL           = "DECIMAL";
    static final String        T_DECLARE           = "DECLARE";
    static final String        T_DEFAULT           = "DEFAULT";
    public static final String T_DELETE            = "DELETE";
    static final String        T_DENSE_RANK        = "DENSE_RANK";
    static final String        T_DEREF             = "DEREF";
    static final String        T_DESCRIBE          = "DESCRIBE";
    static final String        T_DETERMINISTIC     = "DETERMINISTIC";
    static final String        T_DISCONNECT        = "DISCONNECT";
    static final String        T_DISTINCT          = "DISTINCT";
    public static final String T_DOUBLE            = "DOUBLE";
    static final String        T_DROP              = "DROP";
    static final String        T_DYNAMIC           = "DYNAMIC";
    static final String        T_EACH              = "EACH";
    static final String        T_ELEMENT           = "ELEMENT";
    static final String        T_ELSE              = "ELSE";
    static final String        T_END               = "END";
    static final String        T_END_EXEC          = "END_EXEC";
    static final String        T_ESCAPE            = "ESCAPE";
    static final String        T_EVERY             = "EVERY";
    static final String        T_EXCEPT            = "EXCEPT";
    static final String        T_EXEC              = "EXEC";
    public static final String T_EXECUTE           = "EXECUTE";
    static final String        T_EXISTS            = "EXISTS";
    static final String        T_EXP               = "EXP";
    static final String        T_EXTERNAL          = "EXTERNAL";
    static final String        T_EXTRACT           = "EXTRACT";
    static final String        T_FALSE             = "FALSE";
    static final String        T_FETCH             = "FETCH";
    static final String        T_FILTER            = "FILTER";
    public static final String T_FLOAT             = "FLOAT";
    static final String        T_FLOOR             = "FLOOR";
    static final String        T_FOR               = "FOR";
    static final String        T_FOREIGN           = "FOREIGN";
    static final String        T_FREE              = "FREE";
    static final String        T_FROM              = "FROM";
    static final String        T_FULL              = "FULL";
    static final String        T_FUNCTION          = "FUNCTION";
    static final String        T_FUNSION           = "FUSION";
    static final String        T_GET               = "GET";
    static final String        T_GLOBAL            = "GLOBAL";
    public static final String T_GRANT             = "GRANT";
    static final String        T_GROUP             = "GROUP";
    static final String        T_GROUPING          = "GROUPING";
    static final String        T_HAVING            = "HAVING";
    static final String        T_HOLD              = "HOLD";
    public static final String T_HOUR              = "HOUR";
    static final String        T_IDENTITY          = "IDENTITY";
    static final String        T_IN                = "IN";
    static final String        T_INDICATOR         = "INDICATOR";
    static final String        T_INNER             = "INNER";
    static final String        T_INOUT             = "INOUT";
    static final String        T_INSENSITIVE       = "INSENSITIVE";
    public static final String T_INSERT            = "INSERT";
    static final String        T_INT               = "INT";
    public static final String T_INTEGER           = "INTEGER";
    static final String        T_INTERSECT         = "INTERSECT";
    static final String        T_INTERSECTION      = "INTERSECTION";
    public static final String T_INTERVAL          = "INTERVAL";
    static final String        T_INTO              = "INTO";
    static final String        T_IS                = "IS";
    static final String        T_JOIN              = "JOIN";
    static final String        T_LANGUAGE          = "LANGUAGE";
    static final String        T_LARGE             = "LARGE";
    static final String        T_LATERAL           = "LATERAL";
    static final String        T_LEADING           = "LEADING";
    static final String        T_LEFT              = "LEFT";
    static final String        T_LIKE              = "LIKE";
    static final String        T_LIKE_REGX         = "LIKE_REGX";
    static final String        T_LN                = "LN";
    static final String        T_LOCAL             = "LOCAL";
    static final String        T_LOCALTIME         = "LOCALTIME";
    static final String        T_LOCALTIMESTAMP    = "LOCALTIMESTAMP";
    static final String        T_LOWER             = "LOWER";
    static final String        T_MATCH             = "MATCH";
    static final String        T_MAX               = "MAX";
    static final String        T_MEMBER            = "MEMBER";
    static final String        T_MERGE             = "MERGE";
    static final String        T_METHOD            = "METHOD";
    static final String        T_MIN               = "MIN";
    public static final String T_MINUTE            = "MINUTE";
    static final String        T_MOD               = "MOD";
    static final String        T_MODIFIES          = "MODIFIES";
    static final String        T_MODULE            = "MODULE";
    public static final String T_MONTH             = "MONTH";
    static final String        T_MULTISET          = "MULTISET";
    static final String        T_NATIONAL          = "NATIONAL";
    static final String        T_NATURAL           = "NATURAL";
    static final String        T_NCHAR             = "NCHAR";
    static final String        T_NCLOB             = "NCLOB";
    static final String        T_NEW               = "NEW";
    static final String        T_NO                = "NO";
    static final String        T_NONE              = "NONE";
    static final String        T_NORMALIZE         = "NORMALIZE";
    static final String        T_NOT               = "NOT";
    public static final String T_NULL              = "NULL";
    public static final String T_NULLIF            = "NULLIF";
    public static final String T_NUMERIC           = "NUMERIC";
    static final String        T_OCCURRENCES_REGEX = "OCCURRENCES_REGEX";
    static final String        T_OCTECT_LENGTH     = "OCTECT_LENGTH";
    static final String        T_OF                = "OF";
    static final String        T_OLD               = "OLD";
    public static final String T_ON                = "ON";
    static final String        T_ONLY              = "ONLY";
    static final String        T_OPEN              = "OPEN";
    static final String        T_OR                = "OR";
    static final String        T_ORDER             = "ORDER";
    static final String        T_OUT               = "OUT";
    static final String        T_OUTER             = "OUTER";
    static final String        T_OVER              = "OVER";
    static final String        T_OVERLAPS          = "OVERLAPS";
    static final String        T_OVERLAY           = "OVERLAY";
    static final String        T_PARAMETER         = "PARAMETER";
    static final String        T_PARTITION         = "PARTITION";
    static final String        T_PERCENT_RANK      = "PERCENT_RANK";
    static final String        T_PERCENTILE_CONT   = "PERCENTILE_CONT";
    static final String        T_PERCENTILE_DISC   = "PERCENTILE_DISC";
    static final String        T_POSITION          = "POSITION";
    static final String        T_POSITION_REGEX    = "POSITION_REGEX";
    static final String        T_POWER             = "POWER";
    static final String        T_PRECISION         = "PRECISION";
    static final String        T_PREPARE           = "PREPARE";
    static final String        T_PRIMARY           = "PRIMARY";
    static final String        T_PROCEDURE         = "PROCEDURE";
    static final String        T_RANGE             = "RANGE";
    static final String        T_RANK              = "RANK";
    static final String        T_READS             = "READS";
    public static final String T_REAL              = "REAL";
    static final String        T_RECURSIVE         = "RECURSIVE";
    static final String        T_REF               = "REF";
    public static final String T_REFERENCES        = "REFERENCES";
    static final String        T_REFERENCING       = "REFERENCING";
    static final String        T_REGR_AVGX         = "REGR_AVGX";
    static final String        T_REGR_AVGY         = "REGR_AVGY";
    static final String        T_REGR_COUNT        = "REGR_COUNT";
    static final String        T_REGR_INTERCEPT    = "REGR_INTERCEPT";
    static final String        T_REGR_R2           = "REGR_R2";
    static final String        T_REGR_SLOPE        = "REGR_SLOPE";
    static final String        T_REGR_SXX          = "REGR_SXX";
    static final String        T_REGR_SXY          = "REGR_SXY";
    static final String        T_REGR_SYY          = "REGR_SYY";
    static final String        T_RELEASE           = "RELEASE";
    static final String        T_RESULT            = "RESULT";
    static final String        T_RETURN            = "RETURN";
    static final String        T_RETURNS           = "RETURNS";
    static final String        T_REVOKE            = "REVOKE";
    static final String        T_RIGHT             = "RIGHT";
    static final String        T_ROLLBACK          = "ROLLBACK";
    static final String        T_ROLLUP            = "ROLLUP";
    static final String        T_ROW               = "ROW";
    static final String        T_ROW_NUMBER        = "ROW_NUMBER";
    static final String        T_ROWS              = "ROWS";
    static final String        T_SAVEPOINT         = "SAVEPOINT";
    static final String        T_SCOPE             = "SCOPE";
    static final String        T_SCROLL            = "SCROLL";
    static final String        T_SEARCH            = "SEARCH";
    public static final String T_SECOND            = "SECOND";
    public static final String T_SELECT            = "SELECT";
    static final String        T_SENSITIVE         = "SENSITIVE";
    static final String        T_SESSION_USER      = "SESSION_USER";
    public static final String T_SET               = "SET";
    static final String        T_SIMILAR           = "SIMILAR";
    public static final String T_SMALLINT          = "SMALLINT";
    static final String        T_SOME              = "SOME";
    static final String        T_SPECIFIC          = "SPECIFIC";
    static final String        T_SPECIFICTYPE      = "SPECIFICTYPE";
    static final String        T_SQL               = "SQL";
    static final String        T_SQLEXCEPTION      = "SQLEXCEPTION";
    static final String        T_SQLSTATE          = "SQLSTATE";
    static final String        T_SQLWARNING        = "SQLWARNING";
    static final String        T_SQRT              = "SQRT";
    static final String        T_START             = "START";
    static final String        T_STATIC            = "STATIC";
    static final String        T_STDDEV_POP        = "STDDEV_POP";
    static final String        T_STDDEV_SAMP       = "STDDEV_SAMP";
    static final String        T_SUBMULTISET       = "SUBMULTISET";
    static final String        T_SUBSTRING         = "SUBSTRING";
    static final String        T_SUBSTRING_REGEX   = "SUBSTRING_REGEX";
    static final String        T_SUM               = "SUM";
    static final String        T_SYMMETRIC         = "SYMMETRIC";
    static final String        T_SYSTEM            = "SYSTEM";
    static final String        T_SYSTEM_USER       = "SYSTEM_USER";
    static final String        T_TABLE             = "TABLE";
    static final String        T_TABLESAMPLE       = "TABLESAMPLE";
    static final String        T_THEN              = "THEN";
    public static final String T_TIME              = "TIME";
    public static final String T_TIMESTAMP         = "TIMESTAMP";
    public static final String T_TIMEZONE_HOUR     = "TIMEZONE_HOUR";
    public static final String T_TIMEZONE_MINUTE   = "TIMEZONE_MINUTE";
    public static final String T_TO                = "TO";
    static final String        T_TRAILING          = "TRAILING";
    static final String        T_TRANSLATE         = "TRANSLATE";
    static final String        T_TRANSLATE_REGEX   = "TRANSLATE_REGEX";
    static final String        T_TRANSLATION       = "TRANSLATION";
    static final String        T_TREAT             = "TREAT";
    public static final String T_TRIGGER           = "TRIGGER";
    static final String        T_TRIM              = "TRIM";
    static final String        T_TRUE              = "TRUE";
    static final String        T_UESCAPE           = "UESCAPE";
    static final String        T_UNION             = "UNION";
    static final String        T_UNIQUE            = "UNIQUE";
    static final String        T_UNKNOWN           = "UNKNOWN";
    static final String        T_UNNEST            = "UNNEST";
    public static final String T_UPDATE            = "UPDATE";
    static final String        T_UPPER             = "UPPER";
    public static final String T_USER              = "USER";
    static final String        T_USING             = "USING";
    static final String        T_VALUE             = "VALUE";
    static final String        T_VALUES            = "VALUES";
    static final String        T_VAR_POP           = "VAR_POP";
    static final String        T_VAR_SAMP          = "VAR_SAMP";
    public static final String T_VARBINARY         = "VARBINARY";
    public static final String T_VARCHAR           = "VARCHAR";
    static final String        T_VARYING           = "VARYING";
    static final String        T_WHEN              = "WHEN";
    static final String        T_WHENEVER          = "WHENEVER";
    static final String        T_WHERE             = "WHERE";
    static final String        T_WIDTH_BUCKET      = "WIDTH_BUCKET";
    static final String        T_WINDOW            = "WINDOW";
    static final String        T_WITH              = "WITH";
    static final String        T_WITHIN            = "WITHIN";
    static final String        T_WITHOUT           = "WITHOUT";
    public static final String T_YEAR              = "YEAR";

    // ops
    static final String        T_ASTERISK       = "*";
    static final String        T_COMMA          = ",";
    static final String        T_CLOSEBRACKET   = ")";
    static final String        T_EQUALS         = "=";
    public static final String T_DIVIDE         = "/";
    static final String        T_OPENBRACKET    = "(";
    static final String        T_SEMICOLON      = ";";
    static final String        T_MULTIPLY       = "*";
    static final String        T_PERCENT        = "%";
    static final String        T_PLUS           = "+";
    static final String        T_MINUS          = "-";
    static final String        T_QUESTION       = "?";
    static final String        T_LESS           = "<";
    static final String        T_GREATER        = ">";
    static final String        T_NOT_EQUALS     = "<>";
    static final String        T_NOT_EQUALS_ALT = "!=";
    static final String        T_LESS_EQUALS    = "<=";
    static final String        T_GREATER_EQUALS = ">=";
    static final String        T_CONCAT         = "||";

    // non-reserved and other tokens
    static final String        T_SIGNAL             = "SIGNAL";
    static final String        T_SIZE               = "SIZE";
    static final String        T_REPEAT             = "REPEAT";
    static final String        T_RESIGNAL           = "RESIGNAL";
    static final String        T_HEADER             = "HEADER";
    static final String        T_NEXT               = "NEXT";
    static final String        T_ADD                = "ADD";
    static final String        T_ALWAYS             = "ALWAYS";
    static final String        T_ACTION             = "ACTION";
    static final String        T_ADMIN              = "ADMIN";
    static final String        T_AFTER              = "AFTER";
    static final String        T_ALIAS              = "ALIAS";
    static final String        T_ASC                = "ASC";
    static final String        T_AUTOCOMMIT         = "AUTOCOMMIT";
    static final String        T_BACKUP             = "BACKUP";
    static final String        T_BEFORE             = "BEFORE";
    static final String        T_CACHED             = "CACHED";
    static final String        T_CASCADE            = "CASCADE";
    static final String        T_CASEWHEN           = "CASEWHEN";
    static final String        T_CHARACTERS         = "CHARACTERS";
    static final String        T_CHECKPOINT         = "CHECKPOINT";
    static final String        T_CLASS              = "CLASS";
    static final String        T_COLLATION          = "COLLATION";
    static final String        T_COMPACT            = "COMPACT";
    public static final String T_COMPRESSED         = "COMPRESSED";
    static final String        T_DATABASE           = "DATABASE";
    static final String        T_DEFRAG             = "DEFRAG";
    static final String        T_DESC               = "DESC";
    public static final String T_DOW                = "DAYOFWEEK";
    static final String        T_EXPLAIN            = "EXPLAIN";
    static final String        T_FOLD               = "FOLD";
    public static final String T_G_MULTIPLIER       = "G";
    static final String        T_GENERATED          = "GENERATED";
    static final String        T_GRANTED            = "GRANTED";
    static final String        T_IF                 = "IF";
    static final String        T_IFNULL             = "IFNULL";
    static final String        T_IGNORECASE         = "IGNORECASE";
    static final String        T_IMMEDIATELY        = "IMMEDIATELY";
    static final String        T_INCREMENT          = "INCREMENT";
    static final String        T_INDEX              = "INDEX";
    public static final String T_INITIAL            = "INITIAL";
    public static final String T_K_MULTIPLIER       = "K";
    static final String        T_KEY                = "KEY";
    static final String        T_LIMIT              = "LIMIT";
    static final String        T_LOGSIZE            = "LOGSIZE";
    static final String        T_MAXVALUE           = "MAXVALUE";
    public static final String T_M_MULTIPLIER       = "M";
    static final String        T_MATCHED            = "MATCHED";
    static final String        T_MAXROWS            = "MAXROWS";
    static final String        T_MEMORY             = "MEMORY";
    static final String        T_MILLIS             = "MILLIS";
    static final String        T_MINUS_EXCEPT       = "MINUS";
    static final String        T_MINVALUE           = "MINVALUE";
    static final String        T_NOW                = "NOW";
    static final String        T_NOWAIT             = "NOWAIT";
    static final String        T_NVL                = "NVL";
    public static final String T_OBJECT             = "OBJECT";
    static final String        T_OCTET_LENGTH       = "OCTET_LENGTH";
    static final String        T_OCTETS             = "OCTETS";
    static final String        T_OFF                = "OFF";
    static final String        T_OFFSET             = "OFFSET";
    static final String        T_OPTION             = "OPTION";
    public static final String T_OTHER              = "OTHER";
    static final String        T_PARTIAL            = "PARTIAL";
    public static final String T_PASSWORD           = "PASSWORD";
    static final String        T_PLACING            = "PLACING";
    static final String        T_PLAN               = "PLAN";
    static final String        T_PRESERVE           = "PRESERVE";
    static final String        T_PRIVILEGES         = "PRIVILEGES";
    static final String        T_PROPERTY           = "PROPERTY";
    static final String        T_PUBLIC             = "PUBLIC";
    static final String        T_QUEUE              = "QUEUE";
    static final String        T_READONLY           = "READONLY";
    static final String T_REFERENTIAL_INTEGRITY     = "REFERENTIAL_INTEGRITY";
    static final String        T_RENAME             = "RENAME";
    static final String        T_RESTART            = "RESTART";
    static final String        T_RESTRICT           = "RESTRICT";
    static final String        T_ROLE               = "ROLE";
    public static final String T_SCHEMA             = "SCHEMA";
    static final String        T_SCRIPT             = "SCRIPT";
    static final String        T_SCRIPTFORMAT       = "SCRIPTFORMAT";
    static final String        T_SEQUENCE           = "SEQUENCE";
    static final String        T_SESSION            = "SESSION";
    static final String        T_SHUTDOWN           = "SHUTDOWN";
    static final String        T_SIMPLE             = "SIMPLE";
    static final String        T_SOURCE             = "SOURCE";
    static final String        T_SYSDATE            = "SYSDATE";
    static final String        T_TEMP               = "TEMP";
    static final String        T_TEMPORARY          = "TEMPORARY";
    public static final String T_TEXT               = "TEXT";
    public static final String T_TINYINT            = "TINYINT";
    static final String        T_TODAY              = "TODAY";
    static final String        T_TOP                = "TOP";
    static final String        T_TYPE               = "TYPE";
    public static final String T_USAGE              = "USAGE";
    public static final String T_VARCHAR_IGNORECASE = "VARCHAR_IGNORECASE";
    static final String        T_VIEW               = "VIEW";
    static final String        T_WEEK_OF_YEAR       = "WEEK_OF_YEAR";
    static final String        T_WORK               = "WORK";
    static final String        T_WRITE_DELAY        = "WRITE_DELAY";

    //
    //
    //SQL 200n Standard reserved keywords - full set
    public static final int ABS                              = 1;
    public static final int ALL                              = 2;
    public static final int ALLOCATE                         = 3;
    public static final int ALTER                            = 4;
    public static final int AND                              = 5;
    public static final int ANY                              = 6;
    public static final int ARE                              = 7;
    public static final int ARRAY                            = 8;
    public static final int AS                               = 9;
    public static final int ASENSITIVE                       = 10;
    public static final int ASYMMETRIC                       = 11;
    public static final int AT                               = 12;
    public static final int ATOMIC                           = 13;
    public static final int AUTHORIZATION                    = 14;
    public static final int AVG                              = 15;
    public static final int BEGIN                            = 16;
    public static final int BETWEEN                          = 17;
    public static final int BIGINT                           = 18;
    public static final int BINARY                           = 19;
    public static final int BLOB                             = 20;
    public static final int BOOLEAN                          = 21;
    public static final int BOTH                             = 22;
    public static final int BY                               = 23;
    public static final int CALL                             = 24;
    public static final int CALLED                           = 25;
    public static final int CARDINALITY                      = 26;
    public static final int CASCADED                         = 27;
    public static final int CASE                             = 28;
    public static final int CAST                             = 29;
    public static final int CEIL                             = 30;
    public static final int CEILING                          = 31;
    public static final int CHAR                             = 32;
    public static final int CHAR_LENGTH                      = 33;
    public static final int CHARACTER                        = 34;
    public static final int CHARACTER_LENGTH                 = 35;
    public static final int CHECK                            = 36;
    public static final int CLOB                             = 37;
    public static final int CLOSE                            = 38;
    public static final int COALESCE                         = 39;
    public static final int COLLATE                          = 40;
    public static final int COLLECT                          = 41;
    public static final int COLUMN                           = 42;
    public static final int COMMIT                           = 43;
    public static final int CONDITION                        = 44;
    public static final int CONNECT                          = 45;
    public static final int CONSTRAINT                       = 46;
    public static final int CONVERT                          = 47;
    public static final int CORR                             = 48;
    public static final int CORRESPONDING                    = 49;
    public static final int COUNT                            = 50;
    public static final int COVAR_POP                        = 51;
    public static final int COVAR_SAMP                       = 52;
    public static final int CREATE                           = 53;
    public static final int CROSS                            = 54;
    public static final int CUBE                             = 55;
    public static final int CUME_DIST                        = 56;
    public static final int CURRENT                          = 57;
    public static final int CURRENT_CATALOG                  = 58;
    public static final int CURRENT_DATE                     = 59;
    public static final int CURRENT_DEFAULT_TRANSFORM_GROUP  = 60;
    public static final int CURRENT_PATH                     = 61;
    public static final int CURRENT_ROLE                     = 62;
    public static final int CURRENT_SCHEMA                   = 63;
    public static final int CURRENT_TIME                     = 64;
    public static final int CURRENT_TIMESTAMP                = 65;
    public static final int CURRENT_TRANSFORM_GROUP_FOR_TYPE = 66;
    public static final int CURRENT_USER                     = 67;
    public static final int CURSOR                           = 68;
    public static final int CYCLE                            = 69;
    public static final int DATE                             = 70;
    public static final int DAY                              = 71;
    public static final int DEALLOCATE                       = 72;
    public static final int DEC                              = 73;
    public static final int DECIMAL                          = 74;
    public static final int DECLARE                          = 75;
    public static final int DEFAULT                          = 76;
    public static final int DELETE                           = 77;
    public static final int DENSE_RANK                       = 78;
    public static final int DEREF                            = 79;
    public static final int DESCRIBE                         = 80;
    public static final int DETERMINISTIC                    = 81;
    public static final int DISCONNECT                       = 82;
    public static final int DISTINCT                         = 83;
    public static final int DOUBLE                           = 84;
    public static final int DROP                             = 85;
    public static final int DYNAMIC                          = 86;
    public static final int EACH                             = 87;
    public static final int ELEMENT                          = 88;
    public static final int ELSE                             = 89;
    public static final int END                              = 90;
    public static final int END_EXEC                         = 91;
    public static final int ESCAPE                           = 92;
    public static final int EVERY                            = 93;
    public static final int EXCEPT                           = 94;
    public static final int EXEC                             = 95;
    public static final int EXECUTE                          = 96;
    public static final int EXISTS                           = 97;
    public static final int EXP                              = 98;
    public static final int EXTERNAL                         = 99;
    public static final int EXTRACT                          = 100;
    public static final int FALSE                            = 101;
    public static final int FETCH                            = 102;
    public static final int FILTER                           = 103;
    public static final int FLOAT                            = 104;
    public static final int FLOOR                            = 105;
    public static final int FOR                              = 106;
    public static final int FOREIGN                          = 107;
    public static final int FREE                             = 108;
    public static final int FROM                             = 109;
    public static final int FULL                             = 110;
    public static final int FUNCTION                         = 111;
    public static final int FUSION                           = 112;
    public static final int GET                              = 113;
    public static final int GLOBAL                           = 114;
    public static final int GRANT                            = 115;
    public static final int GROUP                            = 116;
    public static final int GROUPING                         = 117;
    public static final int HAVING                           = 118;
    public static final int HOLD                             = 119;
    public static final int HOUR                             = 120;
    public static final int IDENTITY                         = 121;
    public static final int IN                               = 122;
    public static final int INDICATOR                        = 123;
    public static final int INNER                            = 124;
    public static final int INOUT                            = 125;
    public static final int INSENSITIVE                      = 126;
    public static final int INSERT                           = 127;
    public static final int INT                              = 128;
    public static final int INTEGER                          = 129;
    public static final int INTERSECT                        = 130;
    public static final int INTERSECTION                     = 131;
    public static final int INTERVAL                         = 132;
    public static final int INTO                             = 133;
    public static final int IS                               = 134;
    public static final int JOIN                             = 135;
    public static final int LANGUAGE                         = 136;
    public static final int LARGE                            = 137;
    public static final int LATERAL                          = 138;
    public static final int LEADING                          = 139;
    public static final int LEFT                             = 140;
    public static final int LIKE                             = 141;
    public static final int LIKE_REGEX                       = 142;
    public static final int LN                               = 143;
    public static final int LOCAL                            = 144;
    public static final int LOCALTIME                        = 145;
    public static final int LOCALTIMESTAMP                   = 146;
    public static final int LOWER                            = 147;
    public static final int MATCH                            = 148;
    public static final int MAX                              = 149;
    public static final int MEMBER                           = 150;
    public static final int MERGE                            = 151;
    public static final int METHOD                           = 152;
    public static final int MIN                              = 153;
    public static final int MINUTE                           = 154;
    public static final int MOD                              = 155;
    public static final int MODIFIES                         = 156;
    public static final int MODULE                           = 157;
    public static final int MONTH                            = 158;
    public static final int MULTISET                         = 159;
    public static final int NATIONAL                         = 160;
    public static final int NATURAL                          = 161;
    public static final int NCHAR                            = 162;
    public static final int NCLOB                            = 163;
    public static final int NEW                              = 164;
    public static final int NO                               = 165;
    public static final int NONE                             = 166;
    public static final int NORMALIZE                        = 167;
    public static final int NOT                              = 168;
    public static final int NULL                             = 169;
    public static final int NULLIF                           = 170;
    public static final int NUMERIC                          = 171;
    public static final int OCCURRENCES_REGEX                = 172;
    public static final int OCTET_LENGTH                     = 173;
    public static final int OF                               = 174;
    public static final int OLD                              = 175;
    public static final int ON                               = 176;
    public static final int ONLY                             = 177;
    public static final int OPEN                             = 178;
    public static final int OR                               = 179;
    public static final int ORDER                            = 180;
    public static final int OUT                              = 181;
    public static final int OUTER                            = 182;
    public static final int OVER                             = 183;
    public static final int OVERLAPS                         = 184;
    public static final int OVERLAY                          = 185;
    public static final int PARAMETER                        = 186;
    public static final int PARTITION                        = 187;
    public static final int PERCENT_RANK                     = 188;
    public static final int PERCENTILE_CONT                  = 189;
    public static final int PERCENTILE_DISC                  = 190;
    public static final int POSITION                         = 191;
    public static final int POSITION_REGEX                   = 192;
    public static final int POWER                            = 193;
    public static final int PRECISION                        = 194;
    public static final int PREPARE                          = 195;
    public static final int PRIMARY                          = 196;
    public static final int PROCEDURE                        = 197;
    public static final int RANGE                            = 198;
    public static final int RANK                             = 199;
    public static final int READS                            = 200;
    public static final int REAL                             = 201;
    public static final int RECURSIVE                        = 202;
    public static final int REF                              = 203;
    public static final int REFERENCES                       = 204;
    public static final int REFERENCING                      = 205;
    public static final int REGR_AVGX                        = 206;
    public static final int REGR_AVGY                        = 207;
    public static final int REGR_COUNT                       = 208;
    public static final int REGR_INTERCEPT                   = 209;
    public static final int REGR_R2                          = 210;
    public static final int REGR_SLOPE                       = 211;
    public static final int REGR_SXX                         = 212;
    public static final int REGR_SXY                         = 213;
    public static final int REGR_SYY                         = 214;
    public static final int RELEASE                          = 215;
    public static final int RESULT                           = 216;
    public static final int RETURN                           = 217;
    public static final int RETURNS                          = 218;
    public static final int REVOKE                           = 219;
    public static final int RIGHT                            = 220;
    public static final int ROLLBACK                         = 221;
    public static final int ROLLUP                           = 222;
    public static final int ROW                              = 223;
    public static final int ROW_NUMBER                       = 224;
    public static final int ROWS                             = 225;
    public static final int SAVEPOINT                        = 226;
    public static final int SCOPE                            = 227;
    public static final int SCROLL                           = 228;
    public static final int SEARCH                           = 229;
    public static final int SECOND                           = 230;
    public static final int SELECT                           = 231;
    public static final int SENSITIVE                        = 232;
    public static final int SESSION_USER                     = 233;
    public static final int SET                              = 234;
    public static final int SIMILAR                          = 235;
    public static final int SMALLINT                         = 236;
    public static final int SOME                             = 237;
    public static final int SPECIFIC                         = 238;
    public static final int SPECIFICTYPE                     = 239;
    public static final int SQL                              = 240;
    public static final int SQLEXCEPTION                     = 241;
    public static final int SQLSTATE                         = 242;
    public static final int SQLWARNING                       = 243;
    public static final int SQRT                             = 244;
    public static final int START                            = 245;
    public static final int STATIC                           = 246;
    public static final int STDDEV_POP                       = 247;
    public static final int STDDEV_SAMP                      = 248;
    public static final int SUBMULTISET                      = 249;
    public static final int SUBSTRING                        = 250;
    public static final int SUBSTRING_REGEX                  = 251;
    public static final int SUM                              = 252;
    public static final int SYMMETRIC                        = 253;
    public static final int SYSTEM                           = 254;
    public static final int SYSTEM_USER                      = 255;
    public static final int TABLE                            = 256;
    public static final int TABLESAMPLE                      = 257;
    public static final int THEN                             = 258;
    public static final int TIME                             = 259;
    public static final int TIMESTAMP                        = 260;
    public static final int TIMEZONE_HOUR                    = 261;
    public static final int TIMEZONE_MINUTE                  = 262;
    public static final int TO                               = 263;
    public static final int TRAILING                         = 264;
    public static final int TRANSLATE                        = 265;
    public static final int TRANSLATE_REGEX                  = 266;
    public static final int TRANSLATION                      = 267;
    public static final int TREAT                            = 268;
    public static final int TRIGGER                          = 269;
    public static final int TRIM                             = 270;
    public static final int TRUE                             = 271;
    public static final int UESCAPE                          = 272;
    public static final int UNION                            = 273;
    public static final int UNIQUE                           = 274;
    public static final int UNKNOWN                          = 275;
    public static final int UNNEST                           = 276;
    public static final int UPDATE                           = 277;
    public static final int UPPER                            = 278;
    public static final int USER                             = 279;
    public static final int USING                            = 280;
    public static final int VALUE                            = 281;
    public static final int VALUES                           = 282;
    public static final int VAR_POP                          = 283;
    public static final int VAR_SAMP                         = 284;
    public static final int VARBINARY                        = 285;
    public static final int VARCHAR                          = 286;
    public static final int VARYING                          = 287;
    public static final int WHEN                             = 288;
    public static final int WHENEVER                         = 289;
    public static final int WHERE                            = 290;
    public static final int WIDTH_BUCKET                     = 291;
    public static final int WINDOW                           = 292;
    public static final int WITH                             = 293;
    public static final int WITHIN                           = 294;
    public static final int WITHOUT                          = 295;
    public static final int YEAR                             = 296;

    //SQL 200n Standard non-reserved keywords - full set
    public static final int A                           = 301;
    public static final int ABSOLUTE                    = 302;
    public static final int ACTION                      = 303;
    public static final int ADA                         = 304;
    public static final int ADD                         = 305;
    public static final int ADMIN                       = 306;
    public static final int AFTER                       = 307;
    public static final int ALWAYS                      = 308;
    public static final int ASC                         = 309;
    public static final int ASSERTION                   = 310;
    public static final int ASSIGNMENT                  = 311;
    public static final int ATTRIBUTE                   = 312;
    public static final int ATTRIBUTES                  = 313;
    public static final int BEFORE                      = 314;
    public static final int BERNOULLI                   = 315;
    public static final int BREADTH                     = 316;
    public static final int C                           = 317;
    public static final int CASCADE                     = 318;
    public static final int CATALOG                     = 319;
    public static final int CATALOG_NAME                = 320;
    public static final int CHAIN                       = 321;
    public static final int CHARACTER_SET_CATALOG       = 322;
    public static final int CHARACTER_SET_NAME          = 323;
    public static final int CHARACTER_SET_SCHEMA        = 324;
    public static final int CHARACTERISTICS             = 325;
    public static final int CHARACTERS                  = 326;
    public static final int CLASS_ORIGIN                = 327;
    public static final int COBOL                       = 328;
    public static final int COLLATION                   = 329;
    public static final int COLLATION_CATALOG           = 330;
    public static final int COLLATION_NAME              = 331;
    public static final int COLLATION_SCHEMA            = 332;
    public static final int COLUMN_NAME                 = 333;
    public static final int COMMAND_FUNCTION            = 334;
    public static final int COMMAND_FUNCTION_CODE       = 335;
    public static final int COMMITTED                   = 336;
    public static final int CONDITION_NUMBER            = 337;
    public static final int CONNECTION                  = 338;
    public static final int CONNECTION_NAME             = 339;
    public static final int CONSTRAINT_CATALOG          = 340;
    public static final int CONSTRAINT_NAME             = 341;
    public static final int CONSTRAINT_SCHEMA           = 342;
    public static final int CONSTRAINTS                 = 343;
    public static final int CONSTRUCTOR                 = 344;
    public static final int CONTAINS                    = 345;
    public static final int CONTINUE                    = 346;
    public static final int CURSOR_NAME                 = 347;
    public static final int DATA                        = 348;
    public static final int DATETIME_INTERVAL_CODE      = 349;
    public static final int DATETIME_INTERVAL_PRECISION = 350;
    public static final int DEFAULTS                    = 351;
    public static final int DEFERRABLE                  = 352;
    public static final int DEFERRED                    = 353;
    public static final int DEFINED                     = 354;
    public static final int DEFINER                     = 355;
    public static final int DEGREE                      = 356;
    public static final int DEPTH                       = 357;
    public static final int DERIVED                     = 358;
    public static final int DESC                        = 359;
    public static final int DESCRIPTOR                  = 360;
    public static final int DIAGNOSTICS                 = 361;
    public static final int DISPATCH                    = 362;
    public static final int DOMAIN                      = 363;
    public static final int DYNAMIC_FUNCTION            = 364;
    public static final int DYNAMIC_FUNCTION_CODE       = 365;
    public static final int EQUALS                      = 366;
    public static final int EXCEPTION                   = 367;
    public static final int EXCLUDE                     = 368;
    public static final int EXCLUDING                   = 369;
    public static final int FINAL                       = 370;
    public static final int FIRST                       = 371;
    public static final int FOLLOWING                   = 372;
    public static final int FORTRAN                     = 373;
    public static final int FOUND                       = 374;
    public static final int G                           = 375;
    public static final int GENERAL                     = 376;
    public static final int GENERATED                   = 377;
    public static final int GO                          = 378;
    public static final int GOTO                        = 379;
    public static final int GRANTED                     = 380;
    public static final int HIERARCHY                   = 381;
    public static final int IMMEDIATE                   = 382;
    public static final int IMPLEMENTATION              = 383;
    public static final int INCLUDING                   = 384;
    public static final int INCREMENT                   = 385;
    public static final int INITIALLY                   = 386;
    public static final int INPUT                       = 387;
    public static final int INSTANCE                    = 388;
    public static final int INSTANTIABLE                = 389;
    public static final int INVOKER                     = 390;
    public static final int ISOLATION                   = 391;
    public static final int K                           = 392;
    public static final int KEY                         = 393;
    public static final int KEY_MEMBER                  = 394;
    public static final int KEY_TYPE                    = 395;
    public static final int LAST                        = 396;
    public static final int LENGTH                      = 397;
    public static final int LEVEL                       = 398;
    public static final int LOCATOR                     = 399;
    public static final int M                           = 400;
    public static final int MAP                         = 401;
    public static final int MATCHED                     = 402;
    public static final int MAXVALUE                    = 403;
    public static final int MESSAGE_LENGTH              = 404;
    public static final int MESSAGE_OCTET_LENGTH        = 405;
    public static final int MESSAGE_TEXT                = 406;
    public static final int MINVALUE                    = 407;
    public static final int MORE                        = 408;
    public static final int MUMPS                       = 409;
    public static final int NAME                        = 410;
    public static final int NAMES                       = 411;
    public static final int NESTING                     = 412;
    public static final int NEXT                        = 413;
    public static final int NORMALIZED                  = 414;
    public static final int NULLABLE                    = 415;
    public static final int NULLS                       = 416;
    public static final int NUMBER                      = 417;
    public static final int OBJECT                      = 418;
    public static final int OCTETS                      = 419;
    public static final int OPTION                      = 420;
    public static final int OPTIONS                     = 421;
    public static final int ORDERING                    = 422;
    public static final int ORDINALITY                  = 423;
    public static final int OTHERS                      = 424;
    public static final int OUTPUT                      = 425;
    public static final int OVERRIDING                  = 426;
    public static final int PAD                         = 427;
    public static final int PARAMETER_MODE              = 428;
    public static final int PARAMETER_NAME              = 429;
    public static final int PARAMETER_ORDINAL_POSITION  = 430;
    public static final int PARAMETER_SPECIFIC_CATALOG  = 431;
    public static final int PARAMETER_SPECIFIC_NAME     = 432;
    public static final int PARAMETER_SPECIFIC_SCHEMA   = 433;
    public static final int PARTIAL                     = 434;
    public static final int PASCAL                      = 435;
    public static final int PATH                        = 436;
    public static final int PLACING                     = 437;
    public static final int PLI                         = 438;
    public static final int PRECEDING                   = 439;
    public static final int PRESERVE                    = 440;
    public static final int PRIOR                       = 441;
    public static final int PRIVILEGES                  = 442;
    public static final int PUBLIC                      = 443;
    public static final int READ                        = 444;
    public static final int RELATIVE                    = 445;
    public static final int REPEATABLE                  = 446;
    public static final int RESTART                     = 447;
    public static final int RESTRICT                    = 448;
    public static final int RETURNED_CARDINALITY        = 449;
    public static final int RETURNED_LENGTH             = 450;
    public static final int RETURNED_OCTET_LENGTH       = 451;
    public static final int RETURNED_SQLSTATE           = 452;
    public static final int ROLE                        = 453;
    public static final int ROUTINE                     = 454;
    public static final int ROUTINE_CATALOG             = 455;
    public static final int ROUTINE_NAME                = 456;
    public static final int ROUTINE_SCHEMA              = 457;
    public static final int ROW_COUNT                   = 458;
    public static final int SCALE                       = 459;
    public static final int SCHEMA                      = 460;
    public static final int SCHEMA_NAME                 = 461;
    public static final int SCOPE_CATALOG               = 462;
    public static final int SCOPE_NAME                  = 463;
    public static final int SCOPE_SCHEMA                = 464;
    public static final int SECTION                     = 465;
    public static final int SECURITY                    = 466;
    public static final int SELF                        = 467;
    public static final int SEQUENCE                    = 468;
    public static final int SERIALIZABLE                = 469;
    public static final int SERVER_NAME                 = 470;
    public static final int SESSION                     = 471;
    public static final int SETS                        = 472;
    public static final int SIMPLE                      = 473;
    public static final int SIZE                        = 474;
    public static final int SOURCE                      = 475;
    public static final int SPACE                       = 476;
    public static final int SPECIFIC_NAME               = 477;
    public static final int STATE                       = 478;
    public static final int STATEMENT                   = 479;
    public static final int STRUCTURE                   = 480;
    public static final int STYLE                       = 481;
    public static final int SUBCLASS_ORIGIN             = 482;
    public static final int TABLE_NAME                  = 483;
    public static final int TEMPORARY                   = 484;
    public static final int TIES                        = 485;
    public static final int TOP_LEVEL_COUNT             = 486;
    public static final int TRANSACTION                 = 487;
    public static final int TRANSACTION_ACTIVE          = 488;
    public static final int TRANSACTIONS_COMMITTED      = 489;
    public static final int TRANSACTIONS_ROLLED_BACK    = 490;
    public static final int TRANSFORM                   = 491;
    public static final int TRANSFORMS                  = 492;
    public static final int TRIGGER_CATALOG             = 493;
    public static final int TRIGGER_NAME                = 494;
    public static final int TRIGGER_SCHEMA              = 495;
    public static final int TYPE                        = 496;
    public static final int UNBOUNDED                   = 497;
    public static final int UNCOMMITTED                 = 498;
    public static final int UNDER                       = 499;
    public static final int UNNAMED                     = 500;
    public static final int USAGE                       = 501;
    public static final int USER_DEFINED_TYPE_CATALOG   = 502;
    public static final int USER_DEFINED_TYPE_CODE      = 503;
    public static final int USER_DEFINED_TYPE_NAME      = 504;
    public static final int USER_DEFINED_TYPE_SCHEMA    = 505;
    public static final int VIEW                        = 506;
    public static final int WORK                        = 507;
    public static final int WRITE                       = 508;
    public static final int ZONE                        = 509;

    //
    static final int NOT_EQUALS       = 521;
    static final int GREATER          = 522;
    static final int LESS             = 523;
    static final int GREATER_EQUALS   = 524;
    static final int LESS_EQUALS      = 525;
    static final int CONCAT           = 526;
    static final int RIGHT_ARROW_OP   = 527;
    static final int DOUBLE_COLON_OP  = 528;
    static final int DOUBLE_PERIOD_OP = 529;
    static final int DOUBLE_COLUMN_OP = 530;
    static final int COMMA            = 531;
    static final int PLUS             = 532;
    static final int MINUS            = 533;
    static final int ASTERISK         = 534;
    static final int DIVIDE           = 535;
    static final int QUESTION         = 536;
    static final int OPENBRACKET      = 537;
    static final int CLOSEBRACKET     = 538;

    // other token values used as switch cases
    public static final int UNKNOWNTOKEN          = -1;
    static final int        ALIAS                 = 551;
    static final int        AUTOCOMMIT            = 552;
    static final int        CACHED                = 553;
    static final int        CHECKPOINT            = 554;
    static final int        EXPLAIN               = 555;
    static final int        IGNORECASE            = 556;
    static final int        INDEX                 = 557;
    static final int        LOGSIZE               = 558;
    static final int        MAXROWS               = 559;
    static final int        MEMORY                = 560;
    static final int        MINUS_EXCEPT          = 561;
    static final int        PASSWORD              = 563;
    static final int        PLAN                  = 564;
    static final int        PROPERTY              = 565;
    static final int        READONLY              = 566;
    static final int        REFERENTIAL_INTEGRITY = 567;
    static final int        SCRIPT                = 568;
    static final int        SCRIPTFORMAT          = 569;
    static final int        SEMICOLON             = 570;
    static final int        SHUTDOWN              = 571;
    static final int        TEMP                  = 572;
    static final int        TEXT                  = 573;
    static final int        WRITE_DELAY           = 574;
    static final int        DEFRAG                = 575;
    static final int        TOCHAR                = 576;
    static final int        DATABASE              = 577;
    public static final int DAY_OF_WEEK           = 578;
    static final int        INITIAL               = 579;
    static final int        CASEWHEN              = 580;
    static final int        RENAME                = 581;
    static final int        IFNULL                = 583;
    public static final int WEEK_OF_YEAR          = 584;
    static final int        LIMIT                 = 585;
    static final int        OFFSET                = 586;
    static final int        TOP                   = 587;
    static final int        COMPACT               = 588;
    static final int        IMMEDIATELY           = 589;
    static final int        IF                    = 590;
    static final int        MILLIS                = 591;
    static final int        HEADER                = 592;
    static final int        OFF                   = 593;

    //
    static final int X_KEYSET     = 700;
    static final int X_OPTION     = 701;
    static final int X_REPEAT     = 702;
    static final int X_VALUE      = 703;
    static final int X_NAME       = 704;
    static final int X_ENDPARSE   = 705;
    static final int X_STARTPARSE = 706;

    // other
    /*
    static final int IF       = 601;
    static final int REPEAT   = 602;
    static final int RESIGNAL = 603;
    static final int SIGNAL   = 604;
    static final int UNDO     = 605;
    static final int UNTIL    = 606;
    static final int WHILE    = 607;
    static final int ELSEIF   = 608;
    static final int EXIT     = 609;
    static final int HANDLER  = 610;
    static final int ITERATE  = 611;
    static final int LEAVE    = 612;
    static final int LOOP     = 613;
    */
    private static IntValueHashMap reservedKeys = new IntValueHashMap(100);

    static {
        reservedKeys.put(Token.T_ABS, ABS);
        reservedKeys.put(Token.T_ALL, ALL);
        reservedKeys.put(Token.T_ALLOCATE, ALLOCATE);
        reservedKeys.put(Token.T_ALTER, ALTER);
        reservedKeys.put(Token.T_AND, AND);
        reservedKeys.put(Token.T_ANY, ANY);
        reservedKeys.put(Token.T_ARE, ARE);
        reservedKeys.put(Token.T_ARRAY, ARRAY);
        reservedKeys.put(Token.T_AS, AS);
        reservedKeys.put(Token.T_ASENSITIVE, ASENSITIVE);
        reservedKeys.put(Token.T_ASYMMETRIC, ASYMMETRIC);
        reservedKeys.put(Token.T_AT, AT);
        reservedKeys.put(Token.T_ATOMIC, ATOMIC);
        reservedKeys.put(Token.T_AUTHORIZATION, AUTHORIZATION);
        reservedKeys.put(Token.T_AVG, AVG);
        reservedKeys.put(Token.T_BEGIN, BEGIN);
        reservedKeys.put(Token.T_BETWEEN, BETWEEN);
        reservedKeys.put(Token.T_BIGINT, BIGINT);
        reservedKeys.put(Token.T_BINARY, BINARY);
        reservedKeys.put(Token.T_BLOB, BLOB);
        reservedKeys.put(Token.T_BOOLEAN, BOOLEAN);
        reservedKeys.put(Token.T_BOTH, BOTH);
        reservedKeys.put(Token.T_BY, BY);
        reservedKeys.put(Token.T_CALL, CALL);
        reservedKeys.put(Token.T_CALLED, CALLED);
        reservedKeys.put(Token.T_CARDINALITY, CARDINALITY);
        reservedKeys.put(Token.T_CASCADED, CASCADED);
        reservedKeys.put(Token.T_CASE, CASE);
        reservedKeys.put(Token.T_CAST, CAST);
        reservedKeys.put(Token.T_CEIL, CEIL);
        reservedKeys.put(Token.T_CEILING, CEILING);
        reservedKeys.put(Token.T_CHAR, CHAR);
        reservedKeys.put(Token.T_CHAR_LENGTH, CHAR_LENGTH);
        reservedKeys.put(Token.T_CHARACTER, CHARACTER);
        reservedKeys.put(Token.T_CHARACTER_LENGTH, CHARACTER_LENGTH);
        reservedKeys.put(Token.T_CHECK, CHECK);
        reservedKeys.put(Token.T_CLOB, CLOB);
        reservedKeys.put(Token.T_CLOSE, CLOSE);
        reservedKeys.put(Token.T_COALESCE, COALESCE);
        reservedKeys.put(Token.T_COLLATE, COLLATE);
        reservedKeys.put(Token.T_COLLECT, COLLECT);
        reservedKeys.put(Token.T_COLUMN, COLUMN);
        reservedKeys.put(Token.T_COMMIT, COMMIT);
        reservedKeys.put(Token.T_CONDITION, CONDITION);
        reservedKeys.put(Token.T_CONNECT, CONNECT);
        reservedKeys.put(Token.T_CONSTRAINT, CONSTRAINT);
        reservedKeys.put(Token.T_CONVERT, CONVERT);
        reservedKeys.put(Token.T_CORR, CORR);
        reservedKeys.put(Token.T_CORRESPONDING, CORRESPONDING);
        reservedKeys.put(Token.T_COUNT, COUNT);
        reservedKeys.put(Token.T_CONVAR_POP, COVAR_POP);
        reservedKeys.put(Token.T_CONVAR_SAMP, COVAR_SAMP);
        reservedKeys.put(Token.T_CREATE, CREATE);
        reservedKeys.put(Token.T_CROSS, CROSS);
        reservedKeys.put(Token.T_CUBE, CUBE);
        reservedKeys.put(Token.T_CUME_DIST, CUME_DIST);
        reservedKeys.put(Token.T_CURRENT, CURRENT);
        reservedKeys.put(Token.T_CURRENT_CATALOG, CURRENT_CATALOG);
        reservedKeys.put(Token.T_CURRENT_DATE, CURRENT_DATE);
        reservedKeys.put(Token.T_CURRENT_DEFAULT_TRANSFORM_GROUP,
                         CURRENT_DEFAULT_TRANSFORM_GROUP);
        reservedKeys.put(Token.T_CURRENT_PATH, CURRENT_PATH);
        reservedKeys.put(Token.T_CURRENT_ROLE, CURRENT_ROLE);
        reservedKeys.put(Token.T_CURRENT_SCHEMA, CURRENT_SCHEMA);
        reservedKeys.put(Token.T_CURRENT_TIME, CURRENT_TIME);
        reservedKeys.put(Token.T_CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
        reservedKeys.put(Token.T_CURRENT_TRANSFORM_GROUP_FOR_TYPE,
                         CURRENT_TRANSFORM_GROUP_FOR_TYPE);
        reservedKeys.put(Token.T_CURRENT_USER, CURRENT_USER);
        reservedKeys.put(Token.T_CURSOR, CURSOR);
        reservedKeys.put(Token.T_CYCLE, CYCLE);
        reservedKeys.put(Token.T_DATE, DATE);
        reservedKeys.put(Token.T_DAY, DAY);
        reservedKeys.put(Token.T_DEALLOCATE, DEALLOCATE);
        reservedKeys.put(Token.T_DEC, DEC);
        reservedKeys.put(Token.T_DECIMAL, DECIMAL);
        reservedKeys.put(Token.T_DECLARE, DECLARE);
        reservedKeys.put(Token.T_DEFAULT, DEFAULT);
        reservedKeys.put(Token.T_DELETE, DELETE);
        reservedKeys.put(Token.T_DENSE_RANK, DENSE_RANK);
        reservedKeys.put(Token.T_DEREF, DEREF);
        reservedKeys.put(Token.T_DESCRIBE, DESCRIBE);
        reservedKeys.put(Token.T_DETERMINISTIC, DETERMINISTIC);
        reservedKeys.put(Token.T_DISCONNECT, DISCONNECT);
        reservedKeys.put(Token.T_DISTINCT, DISTINCT);
        reservedKeys.put(Token.T_DOUBLE, DOUBLE);
        reservedKeys.put(Token.T_DROP, DROP);
        reservedKeys.put(Token.T_DYNAMIC, DYNAMIC);
        reservedKeys.put(Token.T_EACH, EACH);
        reservedKeys.put(Token.T_ELEMENT, ELEMENT);
        reservedKeys.put(Token.T_ELSE, ELSE);
        reservedKeys.put(Token.T_END, END);
        reservedKeys.put(Token.T_END_EXEC, END_EXEC);
        reservedKeys.put(Token.T_ESCAPE, ESCAPE);
        reservedKeys.put(Token.T_EVERY, EVERY);
        reservedKeys.put(Token.T_EXCEPT, EXCEPT);
        reservedKeys.put(Token.T_EXEC, EXEC);
        reservedKeys.put(Token.T_EXECUTE, EXECUTE);
        reservedKeys.put(Token.T_EXISTS, EXISTS);
        reservedKeys.put(Token.T_EXP, EXP);
        reservedKeys.put(Token.T_EXTERNAL, EXTERNAL);
        reservedKeys.put(Token.T_EXTRACT, EXTRACT);
        reservedKeys.put(Token.T_FALSE, FALSE);
        reservedKeys.put(Token.T_FETCH, FETCH);
        reservedKeys.put(Token.T_FILTER, FILTER);
        reservedKeys.put(Token.T_FLOAT, FLOAT);
        reservedKeys.put(Token.T_FLOOR, FLOOR);
        reservedKeys.put(Token.T_FOR, FOR);
        reservedKeys.put(Token.T_FOREIGN, FOREIGN);
        reservedKeys.put(Token.T_FREE, FREE);
        reservedKeys.put(Token.T_FROM, FROM);
        reservedKeys.put(Token.T_FULL, FULL);
        reservedKeys.put(Token.T_FUNCTION, FUNCTION);
        reservedKeys.put(Token.T_FUNSION, FUSION);
        reservedKeys.put(Token.T_GET, GET);
        reservedKeys.put(Token.T_GLOBAL, GLOBAL);
        reservedKeys.put(Token.T_GRANT, GRANT);
        reservedKeys.put(Token.T_GROUP, GROUP);
        reservedKeys.put(Token.T_GROUPING, GROUPING);
        reservedKeys.put(Token.T_HAVING, HAVING);
        reservedKeys.put(Token.T_HOLD, HOLD);
        reservedKeys.put(Token.T_HOUR, HOUR);
        reservedKeys.put(Token.T_IDENTITY, IDENTITY);
        reservedKeys.put(Token.T_IN, IN);
        reservedKeys.put(Token.T_INDICATOR, INDICATOR);
        reservedKeys.put(Token.T_INNER, INNER);
        reservedKeys.put(Token.T_INOUT, INOUT);
        reservedKeys.put(Token.T_INSENSITIVE, INSENSITIVE);
        reservedKeys.put(Token.T_INSERT, INSERT);
        reservedKeys.put(Token.T_INT, INT);
        reservedKeys.put(Token.T_INTEGER, INTEGER);
        reservedKeys.put(Token.T_INTERSECT, INTERSECT);
        reservedKeys.put(Token.T_INTERSECTION, INTERSECTION);
        reservedKeys.put(Token.T_INTERVAL, INTERVAL);
        reservedKeys.put(Token.T_INTO, INTO);
        reservedKeys.put(Token.T_IS, IS);
        reservedKeys.put(Token.T_JOIN, JOIN);
        reservedKeys.put(Token.T_LANGUAGE, LANGUAGE);
        reservedKeys.put(Token.T_LARGE, LARGE);
        reservedKeys.put(Token.T_LATERAL, LATERAL);
        reservedKeys.put(Token.T_LEADING, LEADING);
        reservedKeys.put(Token.T_LEFT, LEFT);
        reservedKeys.put(Token.T_LIKE, LIKE);
        reservedKeys.put(Token.T_LIKE_REGX, LIKE_REGEX);
        reservedKeys.put(Token.T_LN, LN);
        reservedKeys.put(Token.T_LOCAL, LOCAL);
        reservedKeys.put(Token.T_LOCALTIME, LOCALTIME);
        reservedKeys.put(Token.T_LOCALTIMESTAMP, LOCALTIMESTAMP);
        reservedKeys.put(Token.T_LOWER, LOWER);
        reservedKeys.put(Token.T_MATCH, MATCH);
        reservedKeys.put(Token.T_MAX, MAX);
        reservedKeys.put(Token.T_MEMBER, MEMBER);
        reservedKeys.put(Token.T_MERGE, MERGE);
        reservedKeys.put(Token.T_METHOD, METHOD);
        reservedKeys.put(Token.T_MIN, MIN);
        reservedKeys.put(Token.T_MINUTE, MINUTE);
        reservedKeys.put(Token.T_MOD, MOD);
        reservedKeys.put(Token.T_MODIFIES, MODIFIES);
        reservedKeys.put(Token.T_MODULE, MODULE);
        reservedKeys.put(Token.T_MONTH, MONTH);
        reservedKeys.put(Token.T_MULTISET, MULTISET);
        reservedKeys.put(Token.T_NATIONAL, NATIONAL);
        reservedKeys.put(Token.T_NATURAL, NATURAL);
        reservedKeys.put(Token.T_NCHAR, NCHAR);
        reservedKeys.put(Token.T_NCLOB, NCLOB);
        reservedKeys.put(Token.T_NEW, NEW);
        reservedKeys.put(Token.T_NO, NO);
        reservedKeys.put(Token.T_NONE, NONE);
        reservedKeys.put(Token.T_NORMALIZE, NORMALIZE);
        reservedKeys.put(Token.T_NOT, NOT);
        reservedKeys.put(Token.T_NULL, NULL);
        reservedKeys.put(Token.T_NULLIF, NULLIF);
        reservedKeys.put(Token.T_NUMERIC, NUMERIC);
        reservedKeys.put(Token.T_OCCURRENCES_REGEX, OCCURRENCES_REGEX);
        reservedKeys.put(Token.T_OCTECT_LENGTH, OCTET_LENGTH);
        reservedKeys.put(Token.T_OF, OF);
        reservedKeys.put(Token.T_OLD, OLD);
        reservedKeys.put(Token.T_ON, ON);
        reservedKeys.put(Token.T_ONLY, ONLY);
        reservedKeys.put(Token.T_OPEN, OPEN);
        reservedKeys.put(Token.T_OR, OR);
        reservedKeys.put(Token.T_ORDER, ORDER);
        reservedKeys.put(Token.T_OUT, OUT);
        reservedKeys.put(Token.T_OUTER, OUTER);
        reservedKeys.put(Token.T_OVER, OVER);
        reservedKeys.put(Token.T_OVERLAPS, OVERLAPS);
        reservedKeys.put(Token.T_OVERLAY, OVERLAY);
        reservedKeys.put(Token.T_PARAMETER, PARAMETER);
        reservedKeys.put(Token.T_PARTITION, PARTITION);
        reservedKeys.put(Token.T_PERCENT_RANK, PERCENT_RANK);
        reservedKeys.put(Token.T_PERCENTILE_CONT, PERCENTILE_CONT);
        reservedKeys.put(Token.T_PERCENTILE_DISC, PERCENTILE_DISC);
        reservedKeys.put(Token.T_POSITION, POSITION);
        reservedKeys.put(Token.T_POSITION_REGEX, POSITION_REGEX);
        reservedKeys.put(Token.T_POWER, POWER);
        reservedKeys.put(Token.T_PRECISION, PRECISION);
        reservedKeys.put(Token.T_PREPARE, PREPARE);
        reservedKeys.put(Token.T_PRIMARY, PRIMARY);
        reservedKeys.put(Token.T_PROCEDURE, PROCEDURE);
        reservedKeys.put(Token.T_RANGE, RANGE);
        reservedKeys.put(Token.T_RANK, RANK);
        reservedKeys.put(Token.T_READS, READS);
        reservedKeys.put(Token.T_REAL, REAL);
        reservedKeys.put(Token.T_RECURSIVE, RECURSIVE);
        reservedKeys.put(Token.T_REF, REF);
        reservedKeys.put(Token.T_REFERENCES, REFERENCES);
        reservedKeys.put(Token.T_REFERENCING, REFERENCING);
        reservedKeys.put(Token.T_REGR_AVGX, REGR_AVGX);
        reservedKeys.put(Token.T_REGR_AVGY, REGR_AVGY);
        reservedKeys.put(Token.T_REGR_COUNT, REGR_COUNT);
        reservedKeys.put(Token.T_REGR_INTERCEPT, REGR_INTERCEPT);
        reservedKeys.put(Token.T_REGR_R2, REGR_R2);
        reservedKeys.put(Token.T_REGR_SLOPE, REGR_SLOPE);
        reservedKeys.put(Token.T_REGR_SXX, REGR_SXX);
        reservedKeys.put(Token.T_REGR_SXY, REGR_SXY);
        reservedKeys.put(Token.T_REGR_SYY, REGR_SYY);
        reservedKeys.put(Token.T_RELEASE, RELEASE);
        reservedKeys.put(Token.T_RESULT, RESULT);
        reservedKeys.put(Token.T_RETURN, RETURN);
        reservedKeys.put(Token.T_RETURNS, RETURNS);
        reservedKeys.put(Token.T_REVOKE, REVOKE);
        reservedKeys.put(Token.T_RIGHT, RIGHT);
        reservedKeys.put(Token.T_ROLLBACK, ROLLBACK);
        reservedKeys.put(Token.T_ROLLUP, ROLLUP);
        reservedKeys.put(Token.T_ROW, ROW);
        reservedKeys.put(Token.T_ROW_NUMBER, ROW_NUMBER);
        reservedKeys.put(Token.T_ROWS, ROWS);
        reservedKeys.put(Token.T_SAVEPOINT, SAVEPOINT);
        reservedKeys.put(Token.T_SCOPE, SCOPE);
        reservedKeys.put(Token.T_SCROLL, SCROLL);
        reservedKeys.put(Token.T_SEARCH, SEARCH);
        reservedKeys.put(Token.T_SECOND, SECOND);
        reservedKeys.put(Token.T_SELECT, SELECT);
        reservedKeys.put(Token.T_SENSITIVE, SENSITIVE);
        reservedKeys.put(Token.T_SESSION_USER, SESSION_USER);
        reservedKeys.put(Token.T_SET, SET);
        reservedKeys.put(Token.T_SIMILAR, SIMILAR);
        reservedKeys.put(Token.T_SMALLINT, SMALLINT);
        reservedKeys.put(Token.T_SOME, SOME);
        reservedKeys.put(Token.T_SPECIFIC, SPECIFIC);
        reservedKeys.put(Token.T_SPECIFICTYPE, SPECIFICTYPE);
        reservedKeys.put(Token.T_SQL, SQL);
        reservedKeys.put(Token.T_SQLEXCEPTION, SQLEXCEPTION);
        reservedKeys.put(Token.T_SQLSTATE, SQLSTATE);
        reservedKeys.put(Token.T_SQLWARNING, SQLWARNING);
        reservedKeys.put(Token.T_SQRT, SQRT);
        reservedKeys.put(Token.T_START, START);
        reservedKeys.put(Token.T_STATIC, STATIC);
        reservedKeys.put(Token.T_STDDEV_POP, STDDEV_POP);
        reservedKeys.put(Token.T_STDDEV_SAMP, STDDEV_SAMP);
        reservedKeys.put(Token.T_SUBMULTISET, SUBMULTISET);
        reservedKeys.put(Token.T_SUBSTRING, SUBSTRING);
        reservedKeys.put(Token.T_SUBSTRING_REGEX, SUBSTRING_REGEX);
        reservedKeys.put(Token.T_SUM, SUM);
        reservedKeys.put(Token.T_SYMMETRIC, SYMMETRIC);
        reservedKeys.put(Token.T_SYSTEM, SYSTEM);
        reservedKeys.put(Token.T_SYSTEM_USER, SYSTEM_USER);
        reservedKeys.put(Token.T_TABLE, TABLE);
        reservedKeys.put(Token.T_TABLESAMPLE, TABLESAMPLE);
        reservedKeys.put(Token.T_THEN, THEN);
        reservedKeys.put(Token.T_TIME, TIME);
        reservedKeys.put(Token.T_TIMESTAMP, TIMESTAMP);
        reservedKeys.put(Token.T_TIMEZONE_HOUR, TIMEZONE_HOUR);
        reservedKeys.put(Token.T_TIMEZONE_MINUTE, TIMEZONE_MINUTE);
        reservedKeys.put(Token.T_TO, TO);
        reservedKeys.put(Token.T_TRAILING, TRAILING);
        reservedKeys.put(Token.T_TRANSLATE, TRANSLATE);
        reservedKeys.put(Token.T_TRANSLATE_REGEX, TRANSLATE_REGEX);
        reservedKeys.put(Token.T_TRANSLATION, TRANSLATION);
        reservedKeys.put(Token.T_TREAT, TREAT);
        reservedKeys.put(Token.T_TRIGGER, TRIGGER);
        reservedKeys.put(Token.T_TRIM, TRIM);
        reservedKeys.put(Token.T_TRUE, TRUE);
        reservedKeys.put(Token.T_UESCAPE, UESCAPE);
        reservedKeys.put(Token.T_UNION, UNION);
        reservedKeys.put(Token.T_UNIQUE, UNIQUE);
        reservedKeys.put(Token.T_UNKNOWN, UNKNOWN);
        reservedKeys.put(Token.T_UNNEST, UNNEST);
        reservedKeys.put(Token.T_UPDATE, UPDATE);
        reservedKeys.put(Token.T_UPPER, UPPER);
        reservedKeys.put(Token.T_USER, USER);
        reservedKeys.put(Token.T_USING, USING);
        reservedKeys.put(Token.T_VALUE, VALUE);
        reservedKeys.put(Token.T_VALUES, VALUES);
        reservedKeys.put(Token.T_VAR_POP, VAR_POP);
        reservedKeys.put(Token.T_VAR_SAMP, VAR_SAMP);
        reservedKeys.put(Token.T_VARBINARY, VARBINARY);
        reservedKeys.put(Token.T_VARCHAR, VARCHAR);
        reservedKeys.put(Token.T_VARYING, VARYING);
        reservedKeys.put(Token.T_WHEN, WHEN);
        reservedKeys.put(Token.T_WHENEVER, WHENEVER);
        reservedKeys.put(Token.T_WHERE, WHERE);
        reservedKeys.put(Token.T_WIDTH_BUCKET, WIDTH_BUCKET);
        reservedKeys.put(Token.T_WINDOW, WINDOW);
        reservedKeys.put(Token.T_WITH, WITH);
        reservedKeys.put(Token.T_WITHIN, WITHIN);
        reservedKeys.put(Token.T_WITHOUT, WITHOUT);
        reservedKeys.put(Token.T_YEAR, YEAR);
    }

    private static IntValueHashMap commandSet = new IntValueHashMap(100);

    static {
        commandSet.put(T_IF, Token.IF);
        commandSet.put(T_IFNULL, Token.IFNULL);
        commandSet.put(T_NVL, Token.IFNULL);
        commandSet.put(T_CASEWHEN, Token.CASEWHEN);
        commandSet.put(T_ADD, ADD);
        commandSet.put(T_ADMIN, ADMIN);
        commandSet.put(T_ACTION, ACTION);
        commandSet.put(T_AFTER, AFTER);
        commandSet.put(T_ALIAS, ALIAS);
        commandSet.put(T_ALWAYS, ALWAYS);
        commandSet.put(T_ASC, ASC);
        commandSet.put(T_AUTOCOMMIT, AUTOCOMMIT);
        commandSet.put(T_BEFORE, BEFORE);
        commandSet.put(T_CACHED, CACHED);
        commandSet.put(T_CASCADE, CASCADE);
        commandSet.put(T_CHECKPOINT, CHECKPOINT);
        commandSet.put(T_COMPACT, COMPACT);
        commandSet.put(T_DATABASE, DATABASE);
        commandSet.put(T_DEFRAG, DEFRAG);
        commandSet.put(T_DESC, DESC);
        commandSet.put(T_EXPLAIN, EXPLAIN);
        commandSet.put(T_G_MULTIPLIER, G);
        commandSet.put(T_GENERATED, GENERATED);
        commandSet.put(T_GRANTED, GRANTED);
        commandSet.put(T_HEADER, HEADER);
        commandSet.put(T_IGNORECASE, IGNORECASE);
        commandSet.put(T_IMMEDIATELY, IMMEDIATELY);
        commandSet.put(T_INCREMENT, INCREMENT);
        commandSet.put(T_INDEX, INDEX);
        commandSet.put(T_INITIAL, INITIAL);
        commandSet.put(T_K_MULTIPLIER, K);
        commandSet.put(T_KEY, KEY);
        commandSet.put(T_LIMIT, LIMIT);
        commandSet.put(T_LOGSIZE, LOGSIZE);
        commandSet.put(T_M_MULTIPLIER, M);
        commandSet.put(T_MATCHED, MATCHED);
        commandSet.put(T_MAXROWS, MAXROWS);
        commandSet.put(T_MAXVALUE, MAXVALUE);
        commandSet.put(T_MEMORY, MEMORY);
        commandSet.put(T_MILLIS, MILLIS);
        commandSet.put(T_MINUS_EXCEPT, MINUS_EXCEPT);
        commandSet.put(T_MINVALUE, MINVALUE);
        commandSet.put(T_NEXT, NEXT);
        commandSet.put(T_OFF, OFF);
        commandSet.put(T_OFFSET, OFFSET);
        commandSet.put(T_OPTION, OPTION);
        commandSet.put(T_PARTIAL, PARTIAL);
        commandSet.put(T_PASSWORD, PASSWORD);
        commandSet.put(T_PLACING, PLACING);
        commandSet.put(T_PLAN, PLAN);
        commandSet.put(T_PROPERTY, PROPERTY);
        commandSet.put(T_READONLY, READONLY);
        commandSet.put(T_REFERENTIAL_INTEGRITY, REFERENTIAL_INTEGRITY);
        commandSet.put(T_RENAME, RENAME);
        commandSet.put(T_RESTART, RESTART);
        commandSet.put(T_ROLE, ROLE);
        commandSet.put(T_SCHEMA, SCHEMA);
        commandSet.put(T_SCRIPT, SCRIPT);
        commandSet.put(T_SCRIPTFORMAT, SCRIPTFORMAT);
        commandSet.put(T_SEQUENCE, SEQUENCE);
        commandSet.put(T_SHUTDOWN, SHUTDOWN);
        commandSet.put(T_SIMPLE, SIMPLE);
        commandSet.put(T_SOURCE, SOURCE);
        commandSet.put(T_TEMP, TEMP);
        commandSet.put(T_TEMPORARY, TEMPORARY);
        commandSet.put(T_TEXT, TEXT);
        commandSet.put(T_TOP, TOP);
        commandSet.put(T_TYPE, TYPE);
        commandSet.put(T_USAGE, USAGE);
        commandSet.put(T_VIEW, VIEW);
        commandSet.put(T_WRITE_DELAY, WRITE_DELAY);

        //
        commandSet.put(T_COMMA, Token.COMMA);
        commandSet.put(T_SEMICOLON, SEMICOLON);
        commandSet.put(T_EQUALS, Token.EQUALS);
        commandSet.put(T_NOT_EQUALS_ALT, Token.NOT_EQUALS);
        commandSet.put(T_NOT_EQUALS, Token.NOT_EQUALS);
        commandSet.put(T_LESS, Token.LESS);
        commandSet.put(T_GREATER, Token.GREATER);
        commandSet.put(T_LESS_EQUALS, Token.LESS_EQUALS);
        commandSet.put(T_GREATER_EQUALS, Token.GREATER_EQUALS);
        commandSet.put(T_PLUS, Token.PLUS);
        commandSet.put(T_MINUS, Token.MINUS);
        commandSet.put(T_ASTERISK, Token.ASTERISK);
        commandSet.put(T_DIVIDE, Token.DIVIDE);
        commandSet.put(T_CONCAT, Token.CONCAT);
        commandSet.put(T_QUESTION, Token.QUESTION);
        commandSet.put(T_OPENBRACKET, OPENBRACKET);
        commandSet.put(T_CLOSEBRACKET, CLOSEBRACKET);
    }

    static int get(String token) {

        int type = reservedKeys.get(token, -1);

        if (type == -1) {
            return commandSet.get(token, -1);
        }

        return type;
    }

    public static boolean isCoreKeyword(int token) {
        return coreReservedWords.contains(token);
    }

    public static boolean isKeyword(String token) {
        return reservedKeys.containsKey(token);
    }

    public static int getKeyword(String token, int defaultValue) {
        return reservedKeys.get(token, defaultValue);
    }

    public static int getNonKeyword(String token, int defaultValue) {
        return commandSet.get(token, defaultValue);
    }

    private static OrderedIntHashSet coreReservedWords;

    static {

        // minimal set of identifier not allowed as table / column names
        // these are in effect interpreted as reserved words used by HSQLDB
        coreReservedWords = new OrderedIntHashSet(67, 1);

        short[] keyword = {
            ABS, AS, AND, ALL, ANY, AVG, BY, BETWEEN, BOTH, CALL, CASE, CAST,
            CONVERT, COUNT, COALESCE, CROSS, DISTINCT, ELSE, END, EVERY,
            EXISTS, EXCEPT, EXTRACT, FOR, FROM, FULL, GROUP, HAVING, INTO, IS,
            IN, INTERSECT, JOIN, INNER, LEADING, LIKE, MAX, MIN, NATURAL,
            NULLIF, NOT, ON, ORDER, OR, OUTER, POSITION, PRIMARY, SELECT, SET,
            SOME, STDDEV_POP, STDDEV_SAMP, SUBSTRING, SUM, THEN, TO, TRAILING,
            TRIM, UNIQUE, UNION, USING, VALUES, VAR_POP, VAR_SAMP, WHEN, WHERE,
            DATE, TIME, TIMESTAMP, INTERVAL
        };

        for (int i = 0; i < keyword.length; i++) {
            coreReservedWords.add(keyword[i]);
        }
    }

    public static final short[] SQL_INTERVAL_FIELD_NAMES = new short[] {
        Token.YEAR, Token.MONTH, Token.DAY, Token.HOUR, Token.MINUTE,
        Token.SECOND
    };
    static final HashSet SQL_EXTRACT_FIELD_NAMES = new HashSet();
    static final HashSet SQL_TRIM_SPECIFICATION  = new HashSet();

    static {
        SQL_EXTRACT_FIELD_NAMES.addAll(new Object[] {
            Token.T_YEAR, Token.T_MONTH, Token.T_DAY, Token.T_HOUR,
            Token.T_MINUTE, Token.T_SECOND, Token.T_TIMEZONE_HOUR,
            Token.T_TIMEZONE_MINUTE, Token.T_DOW
        });
        SQL_TRIM_SPECIFICATION.addAll(new Object[] {
            Token.T_LEADING, Token.T_TRAILING, Token.T_BOTH
        });
    }
/*
    static {
        Iterator it = coreReservedWords.iterator();

        while (it.hasNext()) {
            Object key = it.next();

            if (!reservedKeys.containsKey(key)) {
                System.out.println(key);
            }
        }
    }
*/
}
